### PR TITLE
Upgrade to Cordova 6.

### LINKED ISSUE #196: PhoneGap 3.4.1+
It seems like applications using PhoneGap versions lesser than 3.4.1 <a href="https://cordova.apache.org/announcements/2014/11/25/ios-64bit.html">won't be publishable on Apple's App Store</a>. This is consistent with my experiences; I'm getting an "ITMS-90086" error even though my target architectures are "arm64 armv7 armv7s".

Because of this, we should probably finalize and merge the phonegap-3 branch into master.

Could someone elaborate on the state of the phonegap-3 branch? @struan, perhaps?

Cheers!

### LINKED ISSUE #197: Upgrade phonegap
Links to #196 

Also needed for the Maldives

### PR DESCRIPTION
**Pull request by stevenday**
This supersedes #211, #203 and #202 because I merged those all in first
(it was complicated to test and merge them separately after all this time).

I'm mainly putting this up so that beta-testers have somewhere to comment with
issues.

Closes #196, Closes #197

### CODE REVIEW

**Comment by davea** [comment]
Gosh, Apple really don't make it easy to test things do they. The OTA install didn't work because:

 - The manifest and .ipa need to be served over HTTPS
 - The hostname serving the manifest & .ipa needs to match (to some extent) the reverse-DNS bundle identifier. No mention of that in [Apple's docs](http://help.apple.com/deployment/ios/#/apda0e3426d7), of course. If they don't match then clicking the `itms-services://?action=download-manifest&url=...` link does nothing. I edited the manifest to have a bundle id of `io.ngrok.FixMyStreet` and served the whole lot using ngrok which allowed me to click the link and see a 'ngrok.io wants to install FixMyStreet` dialog, but obvs the actual bundle id of the .ipa didn't match so it wouldn't install.

Anyway, I eventually did get it installed via iTunes and it works nicely. The only slight bug I could see was that the navigation buttons ended up beneath the status bar when you tap 'done' to dismiss the keyboard after filling in the problem description:

screen shot 2016-04-22 at 17 46 41

**Comment by dracos** [comment]
* Much easier to install on Android at least ;)
* If possible, I don't think we should ask for the "Read phone status & identity" permission; it's stupid that it's bundled together, but it's the one that lets you see if you're on a call but also steal the user's phone number. So I try and avoid installing things with this permission unless it's a very widely used app.

Seems to work fine :) I realise the following aren't necessarily to do with the framework upgrade, but I thought I'd note them anyway to help in hopefully the near future:
* It looks like #218 might be fixed, yay.
* #217 still seems to be present, though, screenshot (I see from above it is meant to have arrows in the header things too):

* #194 is still present, the tickbox dosn't look much like one.
* Can't seem to get #216 to happen after a few times, will try again over time.
* The map doesn't show OS maps when zoomed out, but Bing ones. Presumably needs updating to match website, I need to get better at keeping things in sync.

**Comment by dracos** [comment]
Just noticed, why are there both https://github.com/mysociety/fixmystreet-mobile/tree/cordova-6/templates and https://github.com/mysociety/fixmystreet-mobile/tree/cordova-6/www/templates/en directories? Has something got confused in the updating/merging, many (all?) seem to be identical.

**Comment by stevenday** [comment]
@davea blimey, what a mission. Thanks for figuring that out!

So I guess we need to put this on the mysociety.org domain in order to share it internally? (I presume they're not mean enough to require that it lives on fixmystreet.mysociety.org?)

**Comment by davea** [comment]
Yep, somewhere on mysociety.org should do the trick. I think fixmystreet.mysociety.org would work, if it makes it easier to host for us.

**Comment by stevenday** [comment]
@dracos - Thanks - I'll have a look at the permissions, I presume they're just a cordova default that I can change. Similarly with the templates, maybe we just forgot to move them when we updated to the new phonegap directory layout

**Comment by stevenday** [comment]
@dracos - re: the templates, it's because the files in `/templates` are translatable, they get compiled into the `www/templates/$language` versions

**Comment by stevenday** [comment]
I've fixed the permissions issue in 9a14f24 - Cordova doesn't let you choose the permissions that different plugins ask for (in this case it's the media plugin requiring 'READ_PHONE_STATE', 'RECORD_AUDIO', 'MODIFY_AUDIO_SETTINGS' and 'RECORD_VIDEO', none of which we need), but you can add a hook to remove things from the manifest file afterwards, so I've done that.

**Comment by stevenday** [comment]
I've fixed the scrolling iOS thing in 59d3e77

**Comment by dracos** [comment]
PR for fixing the maps at #220

**Pull request merged**
