### PR TITLE
Phonegap 3

### PR DESCRIPTION
**Pull request by otmezger**
I found out that some URLs miss a /

this is my first pull request, and I'm not sure if this is a bug or not, so  please consider this carefully. The app did not run before well, and runs well now :-)

### CODE REVIEW

**Comment by stevenday** [comment]
Hi! Thanks so much for taking the time to do this, please don't be put off by the comments, hopefully they're helpful :)

In general, I think it might be useful to split this into multiple pull requests, as you seem to have a few different things going on. These might be:
- Our existing Phonegap 3 changes, plus the changes to the config that I've outlined to make it possible for you to change the settings you need without committing your config changes to the repo. You can bundle the extra comments into this one too. 
- The Spanish translations, adding a .po file and then using gettext to generate the spanish templates, as I described.
- Adding the Google Analytics event and page view tracking.

I hope that's helpful, thanks again for your hard work, we'd really look forward to seeing some of these things being merged in!

**Comment by davea** [comment]
Hey, thanks for your contribution.

We have recently done some work on making the app work with the latest version of Phonegap but these are currently sitting in their [own branch](https://github.com/mysociety/fixmystreet-mobile/tree/makemyisland-rebrand) awaiting us to tidy them up and merge back into master.

This branch also makes i18n and rebranding the app a little easier.

It might be worth waiting until we've got our changes merged into master and then redoing your PR as the changes required will be smaller.

**Comment by otmezger** [comment]
Hi guys, sorry for the late response. I'm a bit overwhelmed with your answers. Now I realised there has been some mistake on my side: I only wanted to merge the thing with the slash on the URLs. 

The thing is: in some parts of the code, you use `CONFIG.FMS_URL + '/something'` and on some others you use `CONFIG.FMS_URL + 'something'` (without the slash)... so changing the value of `CONFIG.FMS_URL` doesn't really helps because there is a part where it breaks anyway. 

Ok, the other things that you mentioned:

* config.js. I didn't realised it was on the repository. I agree, it shouldn't. I ignored config.js on my repository and pushed this change. I think if you ignore it in yours, then it will be ok, nobody could accidentally add it. 
* I didn't understood the part with the .po file. I will look into this later next week.
* Google Analytics: As I mentioned before, I didn't meant to push this code to you. (this is my first merge request). What I did on other projects is to use 2 different ga keys, one for devel and other for productive versions. I'm not completely sure what stevenday meant in his comment. 


In general, we will invest some time with this app in the near future. I would love to contribute. Do you think we could have a hangout so you can explain me what to do better in the future? I could be productive faster and deliver better code to the project. For example, one thing I want to do is to make a new view for visualising the reports, so the app don't "jump" to the web page, but stays right there. I think this could be a nice feature for your app as well.

**Comment by stevenday** [comment]
@otmezger 

> The thing is: in some parts of the code, you use CONFIG.FMS_URL + '/something' and on some others you use CONFIG.FMS_URL + 'something' (without the slash)... so changing the value of CONFIG.FMS_URL doesn't really helps because there is a part where it breaks anyway.

Ah ok, if you want to make a pull request with just that fix in it, that would be great. Note: the easiest way to do this is probably to take a new branch off phonegap3, fix the bits you want in a single commit, and then make a new pull request to the phonegap3 branch (rather than master).

> In general, we will invest some time with this app in the near future. I would love to contribute. Do you think we could have a hangout so you can explain me what to do better in the future? I could be productive faster and deliver better code to the project. 

Great. @struan is the developer who usually manages this code, but he's on holiday for the next couple of weeks. I've sent him an email to show him this PR and ask him about arranging a hangout with our international team to talk to you. Do you have any more details about what you're working on that you could share?

> For example, one thing I want to do is to make a new view for visualising the reports, so the app don't "jump" to the web page, but stays right there. I think this could be a nice feature for your app as well.

We'd definitely be interested in this :)

**Comment by otmezger** [comment]
Ok, great. I'll look into this with my college soon. can't tell exactly when now, but hopefully soon. We are installing the apps in a small city of Costa Rica, it's a nice project and we have a big task, and will use fixmystreet as a base for our project. Other things i would like to wait and share later, once the project goes live, but can talk about it via a hangout.

**Comment by stevenday** [comment]
I'm going to close this since it's been open for a very long time, and we've combined efforts for upgrading phonegap in #202

**Pull request closed without merging**
